name: Test Deploy Cases

on:
  pull_request:

jobs:
  test-pr-update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '18'
        auto-deploy-repos:
          - lando/auto-deploy-action
    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Auto Deploy Action
        uses: ./
        with:
          # Required props
          slug: ${{ matrix.auto-deploy-repos }}
          # Test things
          pr-base: main
          registry: github
          args: --save-dev

  test-direct-update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '14'
        auto-deploy-repos:
          - lando/auto-deploy-action
    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Auto Deploy Action
        uses: ./
        with:
          # Required props
          slug: ${{ matrix.auto-deploy-repos }}
          # Test things
          registry: github
          args: --save-dev
          pr: false
          deploy: false
