name: Test Multiple Directory Cases

on:
  pull_request:

jobs:
  test-multi-dirs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        repos:
          - lando/auto-deploy-action
    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Run Auto Deploy Action
        uses: ./
        with:
          # Required props
          slug: ${{ matrix.repos }}
          # Test things
          package: '@lando/argv'
          args: -D
          deploy: false
          dirs: ./,./test
          pr: false
          update: true
          version: latest

